version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://MARKTAB:password@db/MARKTAB
      - RUST_LOG=info
    depends_on:
      - db
    volumes:
      - ./uploads:/opt/MARKTAB/uploads
      - ./backups:/opt/MARKTAB/backups
    restart: always

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MARKTAB
      - MYSQL_USER=MARKTAB
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data: 